Item controller 2
alangarciac/app-rest pull request #15
Opened 2021-03-09 16:29 UTC by cdpiazza

Agregada al capa DAO

2021-03-10 15:22 UTC, alangarciac requested changes
Quizás el DAO está teniendo toda la responsabilidad. Solo enmascaría las exceptions en el DAO y dejaría al service el logging catcheando las exceptions del tipo `ItemException*`

Re-utilizaría la interfaz Checkeable para que todos los DTOs queden consistentes con la misma interfaz.

Haría el AbstracDAO, ya que vamos a interfacear, para que quede genérico y lo utilicen todos los DAOs

Bien por la interfaz del DAO, buena iniciativa.

Avisame cualquier cosa, lo vemos!

2021-03-10 15:22 UTC, alangarciac commented on src/main/java/com/app/rest/dao/interfaces/ItemDAO.java
> +public interface ItemDAO {
Esta interface podría llamarse `AbstractDAO` y que la implementen todos los DAOs de la app

2021-03-10 15:22 UTC, alangarciac commented on src/main/java/com/app/rest/dao/impl/ItemDAOHibernateImpl.java
> +    public ItemDTO findById(Long id) throws ItemNotFoundException, ItemException {
Faltarían los `@Override` cuando se implementa una interfaz, se coloca el `@Override` para denotar que se se está implementando el método de la interfaz

2021-03-10 15:22 UTC, alangarciac commented on src/main/java/com/app/rest/model/dto/ItemValidator.java
> +    void validate() throws ItemValidateException, ItemTypeException;
podríamos utlizar la interfaz ya definida `Checkeable`, para que quede consistente todos los DTOs con la misma interfaz

2021-03-10 15:22 UTC, alangarciac commented on src/main/java/com/app/rest/service/ItemService.java
> +        return itemDAO.findById(id);
acá podrías hacer el try/catch de ItemException y loguear el error. De esta forma el logging para ItemException y manejo de la misma queda en el service.

2021-03-10 15:34 UTC, cdpiazza commented on src/main/java/com/app/rest/dao/interfaces/ItemDAO.java
> +public interface ItemDAO {
oki

2021-03-10 15:35 UTC, cdpiazza commented on src/main/java/com/app/rest/dao/interfaces/ItemDAO.java
> +public interface ItemDAO {
En realidad, ahi tenemos un tema porque la interfaz tiene que tener las excepciones que se van a levantar, y ahi dejaria de ser abstracto, porque item tiene las de item, order las de order, etc.

2021-03-10 15:36 UTC, cdpiazza commented on src/main/java/com/app/rest/dao/impl/ItemDAOHibernateImpl.java
> +    public ItemDTO findById(Long id) throws ItemNotFoundException, ItemException {
oki

2021-03-10 15:38 UTC, cdpiazza commented on src/main/java/com/app/rest/model/dto/ItemValidator.java
> +    void validate() throws ItemValidateException, ItemTypeException;
igual que con la interfaz del dao, tenemos un tema con las posibles excepciones, quedan pegadas al tipo de DTO, no se puede generalizar... o al menos no se como facilmente.

2021-03-10 15:38 UTC, cdpiazza commented on src/main/java/com/app/rest/service/ItemService.java
> +        return itemDAO.findById(id);
oki!

2021-03-10 15:39 UTC, cdpiazza commented on src/main/java/com/app/rest/service/ItemService.java
> +        return itemDAO.findById(id);
pero no se deberian loguear los posibles problemas de DDBB en el dao q es el que se conecta con la BBDD??

2021-03-10 15:39 UTC, cdpiazza commented on src/main/java/com/app/rest/service/ItemService.java
> +        return itemDAO.findById(id);
o vos decis de loguear en cada lugar una cosa, en el dao los posibles persistance error y en el service otras cosa?

2021-03-10 15:47 UTC, cdpiazza commented on src/main/java/com/app/rest/service/ItemService.java
> +        return itemDAO.findById(id);
bueno lo resuelvo loggueando en el service, creo un tipo de excepcion nuevo para encapsular los persistance

2021-03-10 15:53 UTC, alangarciac commented on src/main/java/com/app/rest/dao/interfaces/ItemDAO.java
> +public interface ItemDAO {
En ese caso las exceptions deberían pasar a heredar de `RuntimeException`

2021-03-10 15:56 UTC, alangarciac commented on src/main/java/com/app/rest/model/dto/ItemValidator.java
> +    void validate() throws ItemValidateException, ItemTypeException;
utilziando `Checkeable` la validéz de un item queda sujeta a el booleano de retorno, despe mi punto de vista queda mas claro y no tenes problemas de exceptiosn en method signature. El método isSupported() retorna true o false, no dispara exceptions. Si existen se manejan internamente en el isSupported y retornaría false.

2021-03-10 15:57 UTC, alangarciac commented on src/main/java/com/app/rest/service/ItemService.java
> +        return itemDAO.findById(id);
_el dao los posibles persistance error y en el service otras cosa?_ esto mismo, el DAO que loguee problemas de la base o de su manejador, en este caso Hibernate o la interfaz JPA

2021-03-10 16:00 UTC, cdpiazza commented on src/main/java/com/app/rest/dao/interfaces/ItemDAO.java
> +public interface ItemDAO {
Por claridad prefiero q sean interfaces separadas y no olvidarme de catchear excepciones q hacerlas runtime y comermela en algun lado, es para peor no te parece?

2021-03-10 16:01 UTC, cdpiazza commented on src/main/java/com/app/rest/model/dto/ItemValidator.java
> +    void validate() throws ItemValidateException, ItemTypeException;
Bueno eso me cambia todo el manejo :(

2021-03-10 16:03 UTC, cdpiazza commented on src/main/java/com/app/rest/service/ItemService.java
> +        return itemDAO.findById(id);
bueno entonces el service igual no loguea casi nada, porque que haya un error de tipo, o un error de notfound, no son errores logueables, quedan para debbug nada mas. los logueo con ese clasificador

2021-03-10 16:14 UTC, cdpiazza commented on src/main/java/com/app/rest/model/dto/ItemValidator.java
> +    void validate() throws ItemValidateException, ItemTypeException;
El tema es que devolver simplemente un true,false, no me sirve para el validate porque hay distintos tipos de errores.

Ahi veo q haciendo q tire Exception generico, puedo hacer la interfaz, fijate a ver q te parece hacerlo asi.

2021-03-10 20:21 UTC, alangarciac reviewed
algunos cambios, minimos

2021-03-10 20:21 UTC, alangarciac commented on src/main/java/com/app/rest/controller/ItemController.java
> +    @GetMapping("/items/{X_type}")
{type} quedaria mejor, era un ejemplo lo del trello jajaja

2021-03-10 20:21 UTC, alangarciac commented on src/main/java/com/app/rest/dao/interfaces/ItemDAO.java
> +@Service
no hace falta esta anotación para la interface

2021-03-10 20:21 UTC, alangarciac commented on src/main/java/com/app/rest/exception/itemExceptions/ItemNotFoundException.java
> +public class ItemNotFoundException extends Exception {
podría extender de ItemException en lugar de extender de Exception

2021-03-10 20:21 UTC, alangarciac commented on src/main/java/com/app/rest/exception/itemExceptions/ItemPersistanceException.java
> +public class ItemPersistanceException extends Exception {
lo mismo aca, podria extender de ItemException

2021-03-10 20:21 UTC, alangarciac commented on src/main/java/com/app/rest/exception/itemExceptions/ItemPersistanceException.java
> +public class ItemPersistanceException extends Exception {
TYPO en Persist**a**nce > Persistence

2021-03-10 20:21 UTC, alangarciac commented on src/main/java/com/app/rest/exception/itemExceptions/ItemTypeException.java
>  public class ItemTypeException extends Exception {
podria extender de ItemException

2021-03-10 20:21 UTC, alangarciac commented on src/main/java/com/app/rest/model/dto/Checkable.java
> +    void validate() throws Exception;
Si vamos a ir por validate con exception, podría throwear un `ValidationException`. Eliminaría el  boolean isSupported();

2021-03-11 01:21 UTC, cdpiazza commented on src/main/java/com/app/rest/model/dto/Checkable.java
> +    void validate() throws Exception;
aa me gusta esa de validation exception y listo, qda generico

2021-03-11 01:22 UTC, cdpiazza commented on src/main/java/com/app/rest/exception/itemExceptions/ItemTypeException.java
>  public class ItemTypeException extends Exception {
creo q no cambia mucho, pero bueno como quieras

2021-03-11 01:22 UTC, cdpiazza commented on src/main/java/com/app/rest/dao/interfaces/ItemDAO.java
> +@Service
qdo del copypaste

2021-03-11 01:22 UTC, cdpiazza commented on src/main/java/com/app/rest/controller/ItemController.java
> +    @GetMapping("/items/{X_type}")
bueno, quiza hacia algo q se yo

2021-03-11 01:24 UTC, cdpiazza commented on src/main/java/com/app/rest/exception/itemExceptions/ItemPersistanceException.java
> +public class ItemPersistanceException extends Exception {
Ups

2021-03-11 03:47 UTC, alangarciac commented on src/main/java/com/app/rest/exception/itemExceptions/ItemTypeException.java
>  public class ItemTypeException extends Exception {
queda mas ordenado:

                            ItemException
                                      |
          ------------------------------------------------
          |                               |                        |
ItemNotFound      ItemPersistence        ItemType

*alto dibujo me mandé eee

2021-03-11 13:45 UTC, cdpiazza commented on src/main/java/com/app/rest/exception/itemExceptions/ItemNotFoundException.java
> +public class ItemNotFoundException extends Exception {
Se rompen los handlers cuando lo haces heredar de itemException porq lo toma como la misma excepcion en el catch, para esto hay q hacer una excepcion general y una excepcion padre, lo hago y de ultima despues lo borramos.

2021-03-11 17:14 UTC, alangarciac approved these changes
impeca!

2021-03-11 17:16 UTC, merged