Crear ABM de pedido en controller
alangarciac/app-rest pull request #4
Opened 2021-02-18 14:04 UTC by zeeno77

modified:   src/main/java/com/app/rest/controller/AppController.java	
modified:   src/main/java/com/app/rest/service/ServicioPedido.java

[Aclaracion] Como no estan definidas, presupongo que las funciones de los services siguen el siguiente patron:
get|post|delete + nombre de la funcion del controller.
Si llegan a ser distintas se cambian en el fututo

2021-02-18 20:48 UTC, alangarciac requested changes
Impecable, antes de seguir tirando codigo, hagamos el refactor a **english**. 

- Creé esta tarea https://trello.com/c/ENmuyS4c/6-refactor-to-english

2021-02-18 20:48 UTC, alangarciac commented on src/main/java/com/app/rest/controller/AppController.java
> +    @GetMapping("/pedidos/{id}")
Haría renames, antes de seguir tirando codigo, pasando a english. Subí un modelo a seguir (https://trello.com/c/wOy2hkEm/1-soporte-de-bd-mysql) para estar alineados con eso inicialmente, de esta forma `pedido` pasaria a ser > `order`

2021-02-18 20:48 UTC, alangarciac commented on src/main/java/com/app/rest/controller/AppController.java
> +    @GetMapping("/pedidos/{id}")
el get de un element iría en singular:` /order/{id}`

2021-02-18 20:48 UTC, alangarciac commented on src/main/java/com/app/rest/controller/AppController.java
> +    @DeleteMapping("/pedidos/{id}")
Lo mismo acá, pasaría a ser `/order/{id}`

2021-02-18 20:48 UTC, alangarciac commented on src/main/java/com/app/rest/controller/AppController.java
> +    @PostMapping("/pedidos/nuevo")
`/order/new`

2021-02-19 20:26 UTC, alangarciac approved these changes, later dismissed

2021-02-19 23:47 UTC, zeeno77 commented
Terminado el Refactoring a Ingles de todo el Proyecto

2021-02-21 20:33 UTC, alangarciac approved these changes

2021-02-21 20:33 UTC, alangarciac commented on src/main/java/com/app/rest/model/Order.java
> +public class Order {
Acá creo que Tato lo modeló en su branch, es probable que tenga conflicto.

2021-02-21 20:38 UTC, alangarciac commented
Loego de resolver conflictos con master, se podría mergear para seguir iterando en un nuevo branch en caso de ser necesario.

2021-02-22 01:22 UTC, closed without merging